spring:
  main:
    banner-mode: off

  application:
    name: java-reactive-microservices-chassis-integration-test

  h2:
    console:
      enabled: off

  sql:
    init:
      mode: never

  liquibase:
    change-log: "db/changelog/db-test.changelog-master.xml"
    test-rollback-on-update: on
    contexts: test

  r2dbc:
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  codec:
    log-request-details: on

server:
  error:
    include-exception: on
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

client:
  base-url: https://mock.server.com

springdoc:
  api-docs:
    enabled: off

apidoc:
  title: Java Reactive RESTful Service Test
  description: RESTful Service Test for Reactive Restful API with Spring Boot
  version: TEST

debug: off
trace: off
logging:
  level:
    root: error
    web: trace
    sql: trace
    reactor:
      netty:
        http:
          client: debug
    org:
      testcontainers: trace
      springframework:
        jdbc: trace
        r2dbc: trace
    liquibase:
      database: trace
