version: "3.9"

services:
  chassis:
    container_name: chassis-openj9
    image: chassis:openj9
    build:
      context: .
    networks:
    - microservice
    ports:
    - "8080:8080"
    volumes:
    - db_credentials:/opt/app/reactive-microservice/db
    - log:/var/log/reactive-microservice

volumes:
  db_credentials:
    name: db-data
  log:
    name: log-data

networks:
  microservice:
    name: microservice-network
