spring:
  application:
    name: @project.name@

  config:
    import: "file:db/config.yaml"

  codec:
    log-request-details: on

server:
  port: 8080
  error:
    include-exception: on
    include-stacktrace: always

springdoc:
  api-docs:
    enabled: on
    path: /api-docs

debug: off
trace: off
logging:
  file:
    name: ${spring.application.name}.log
  level:
    root: error
    web: trace
    sql: trace
    org:
      springframework:
        jdbc:
          datasource: trace
        r2dbc: trace

