spring:
  config:
    import: "configtree:db/"

  application:
    name: @project.name@

  h2:
    console:
      enabled: off

  sql:
    init:
      mode: never

  liquibase:
    url: jdbc:${liquibase.database}
    user: ${liquibase.username:sa}
    password: ${liquibase.password}
    test-rollback-on-update: on

  r2dbc:
    url: r2dbc:pool:${app.database}
    username: ${app.username:sa}
    password: ${app.password}
    pool:
      initial-size: 10
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  codec:
    log-request-details: on

server:
  port: 8080
  error:
    include-exception: on
    include-stacktrace: always

springdoc:
  api-docs:
    enabled: on
    path: /api-docs

debug: off
trace: off
logging:
  file:
    name: ${spring.application.name}.log
  level:
    root: error
    web: trace
    sql: trace
    org:
      springframework:
        jdbc:
          datasource: trace
        r2dbc: trace

