debug: off

server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always

spring:
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    test-rollback-on-update: true
    url: jdbc:h2:file:./target/test-data/chassisdb
    user: sa
    password:

springdoc:
  api-docs:
    enabled: true

