spring:
  main:
    banner-mode: log
  config:
    import: "configtree:db/"

  application:
    name: @project.artifactId@

  h2:
    console:
      enabled: off

  sql:
    init:
      mode: never

  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
    url: jdbc:${liquibase.database}
    user: ${liquibase.username:sa}
    password: ${liquibase.password}
    contexts: prod
    test-rollback-on-update: on

  r2dbc:
    url: r2dbc:pool:${app.database}
    username: ${app.username:sa}
    password: ${app.password}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

  codec:
    log-request-details: on

server:
  port: 8080

client:
  base-url: https://api.github.com

management:
  server:
    port: @management.port@
  endpoints:
    web:
      exposure:
        include: health, openapi, swaggerui # For yaml format access /actuator/openapi/springdocDefault/yaml

springdoc:
  use-management-port: on
  show-actuator: on

apidoc:
  title: @project.name@
  description: @project.description@
  version: @project.version@

debug: off
trace: off
logging:
  file:
    path: /var/log/spring-boot/@build.name@
  level:
    root: error
    web: trace
    sql: trace
    org:
      springframework:
        jdbc: trace
        r2dbc: trace
    liquibase:
      database: trace
