= AsciiDoc Example Document
Berchris Requiao <berchris.requiao@neueda.com>
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

:sourcedir: ../main/java/com/neueda/microservice/reactive

[[abstract]]

This _Hello World_ document has been written in `plain text` with
http://asciidoc.org[AsciiDoc].

[TIP]
Use http://asciidoctor.org[Asciidoctor] to convert AsciiDoc into other formats.
footnote:[Not to mention the final result is amazing!]. It provides built-in converters
for three formats by default: https://docs.asciidoctor.org/asciidoctor/latest/html-backend[HTML5],
https://docs.asciidoctor.org/asciidoctor/latest/docbook-backend[DocBook4], and
https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend[man page]. Feel free to
icon:twitter[role=aqua] about it!

[[sample-section]]
== List Items Sample Section
[square]
* <<list-chassis, List chassis items>>
* <<github, List GitHub users>>
* <<contract-testing, Contract testing>>

[[router-handler]]
== Router Handler Function
====
[source,java,indent=0,role="primary]
.Retrieve
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=retrieve]
----
<1> Convert the `Entity` object into a `Model` one.

[source,java,indent=0,role="secondary"]
.Create
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=create]
----
<1> Process a validation from the request body object.
<2> Add the validated request body object into database.
====

[[list-demo]]
== List all chassis items
====
operation::chassis-controller-tests/should-retrieve-all-chassis-items[snippets='curl-request,httpie-request,http-request,http-response']
====

[[github]]
== List GitHub users
====
operation::chassis-controller-tests/should-retrieve-chassis-client-response[snippets='curl-request,httpie-request,http-request,http-response']
====

[[contract-testing]]
== Contract testing list all chassis
====
operation::chassis-test/validate_should_list_all_chassis_items[snippets='curl-request,httpie-request,http-request,http-response']
====
