= AsciiDoc Example Document
Berchris Requiao <berchris.requiao@neueda.com>
:icons: font
:source-highlighter: highlightjs
//:toc: left
//:toclevels: 3
:sectlinks:

:sourcedir: ../main/java/com/neueda/microservice/reactive
:test-resources: ../test/resources

:block-switch: https://github.com/spring-io/spring-asciidoctor-extensions#block-switch
:snippet-templates: https://github.com/spring-projects/spring-restdocs/tree/v2.0.5.RELEASE/spring-restdocs-core/src/main/resources/org/springframework/restdocs/templates/asciidoctor
:snippet-customize: https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-customizing-snippets

[[abstract]]

This _Hello World_ document has been written in `plain text` with
http://asciidoc.org[AsciiDoc].

[TIP]
Use http://asciidoctor.org[Asciidoctor] to convert AsciiDoc into other formats.
footnote:[Not to mention the final result is amazing!]. It provides built-in converters
for three formats by default: https://docs.asciidoctor.org/asciidoctor/latest/html-backend[HTML5],
https://docs.asciidoctor.org/asciidoctor/latest/docbook-backend[DocBook4], and
https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend[man page]. Feel free to
icon:twitter[role=aqua] about it!


[[sample-section]]
== List Items Sample Section

[square]
* <<list-chassis, List chassis items>>
* <<github, List GitHub users>>
* <<contract-testing, Contract testing>>


[[router-handler]]
== Router Handler Function

====
.Retrieve
[source,java,indent=0,role="primary"]
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=retrieve]
----
<1> Convert the `Entity` object into a `Model` one.

.Create
[source,java,indent=0,role="secondary"]
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=create]
----
<1> Process a validation from the request body object.
<2> Add the validated request body object into database.
====
NOTE: This project uses the {block-switch}[Block Switch Spring Asciidoctor Extension^].

[[block-switch]]
== Use Block Switch with Generated Snippets
Spring REST Docs uses {snippet-templates}[default templates^] to automatically generates the API snippets.
To allow the generated snippets properly works with `Block Switch Spring Asciidoctor Extension` it is required to
{snippet-customize}[customize the generated snippets^] yourself. The following example shows how to do so:

====
.Primary
[source,adoc]
....
include::{test-resources}/org/springframework/restdocs/templates/asciidoctor/curl-request.snippet[]
....

.Secondary
[source,adoc]
....
include::{test-resources}/org/springframework/restdocs/templates/asciidoctor/httpie-request.snippet[]
....
====


[[list-chassis]]
== List all chassis items

=== Request
====
.Curl
include::{snippets}/chassis-controller-tests/should-retrieve-all-chassis-items/curl-request.adoc[]

.HTTPie
include::{snippets}/chassis-controller-tests/should-retrieve-all-chassis-items/httpie-request.adoc[]

.HTTP
include::{snippets}/chassis-controller-tests/should-retrieve-all-chassis-items/http-request.adoc[]
====
NOTE: The Spring REST Docs uses
https://github.com/spring-projects/spring-restdocs/tree/v2.0.5.RELEASE/spring-restdocs-core/src/main/resources/org/springframework/restdocs/templates/asciidoctor[default templates^]
to generates its snippets.
To allow the generated snippets works with `Block Switch Spring Asciidoctor Extension` properly it is required to
https://docs.spring.io/spring-restdocs/docs/current/reference/html5/#documenting-your-api-customizing-snippets[customize the generated snippets^].

=== Response
====
include::{snippets}/chassis-controller-tests/should-retrieve-all-chassis-items/http-response.adoc[]
====


[[github]]
== List GitHub users

=== Request
====
.Curl
include::{snippets}/chassis-controller-tests/should-retrieve-chassis-client-response/curl-request.adoc[]

.HTTPie
include::{snippets}/chassis-controller-tests/should-retrieve-chassis-client-response/httpie-request.adoc[]

.HTTP
include::{snippets}/chassis-controller-tests/should-retrieve-chassis-client-response/http-request.adoc[]
====

=== Response
====
include::{snippets}/chassis-controller-tests/should-retrieve-chassis-client-response/http-response.adoc[]
====


[[contract-testing]]
== Contract testing list all chassis items

=== Request
====
.Curl
include::{snippets}/chassis-test/validate_should_list_all_chassis_items/curl-request.adoc[]

.HTTPie
include::{snippets}/chassis-test/validate_should_list_all_chassis_items/httpie-request.adoc[]

.HTTP
include::{snippets}/chassis-test/validate_should_list_all_chassis_items/http-request.adoc[]
====

=== Response
====
include::{snippets}/chassis-test/validate_should_list_all_chassis_items/http-response.adoc[]
====
