= AsciiDoc Example Initial Document
Doc Writer <berchris.requiao@neueda.com>
:icons: font
:sourcedir: ../main/java/com/neueda/microservice/reactive

This _Hello World_ document has been written in `plain text` with
http://asciidoc.org[AsciiDoc].

[TIP]
Use http://asciidoctor.org[Asciidoctor] to convert AsciiDoc into other formats.
footnote:[Not to mention the final result is amazing!]. It provides built-in converters
for three formats by default: https://docs.asciidoctor.org/asciidoctor/latest/html-backend[HTML5],
https://docs.asciidoctor.org/asciidoctor/latest/docbook-backend[DocBook4], and
https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend[man page]. Feel free to
icon:twitter[role=aqua] about it!

== List Items Sample Section
[square]
* item 1
* item 2

== Router Handler Function
====
[source,java,indent=0,role="primary]
.Retrieve an item
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=retrieve]
----
<1> Convert the Entity object into a Model one

[source,java,indent=0,role="secondary"]
.Create an item
----
include::{sourcedir}/handler/ChassisRouterHandler.java[tag=create]
----
<1> Process a validation from the request body object
<2> Add the validated request body object into database
====

== List all chassis call
operation::chassis-controller-tests/should-retrieve-all-chassis-items[snippets='curl-request,httpie-request,http-request,http-response']

== GitHub search username
operation::chassis-controller-tests/should-retrieve-chassis-client-response[snippets='curl-request,httpie-request,http-request,http-response']

== Contract testing list all chassis
operation::chassis-test/validate_should_list_all_chassis_items[snippets='curl-request,httpie-request,http-request,http-response']
